// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDiQdPOumm9NaoZn-lCA9YOrqCbI16Yw',
    appId: '1:157676629757:web:f6324d183194d2aef81894',
    messagingSenderId: '157676629757',
    projectId: 'certin-70cf9',
    authDomain: 'certin-70cf9.firebaseapp.com',
    storageBucket: 'certin-70cf9.appspot.com',
    measurementId: 'G-VSSESYL096',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDie1kXa139hhDBnDI6slhky9TRLu-TFPQ',
    appId: '1:157676629757:android:428e62944958b040f81894',
    messagingSenderId: '157676629757',
    projectId: 'certin-70cf9',
    storageBucket: 'certin-70cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiy3gXC0B0Jd7GyyYIhV51ZlvaDawcLAE',
    appId: '1:157676629757:ios:f8d2c2ba95f860f9f81894',
    messagingSenderId: '157676629757',
    projectId: 'certin-70cf9',
    storageBucket: 'certin-70cf9.appspot.com',
    iosBundleId: 'com.example.certin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiy3gXC0B0Jd7GyyYIhV51ZlvaDawcLAE',
    appId: '1:157676629757:ios:f8d2c2ba95f860f9f81894',
    messagingSenderId: '157676629757',
    projectId: 'certin-70cf9',
    storageBucket: 'certin-70cf9.appspot.com',
    iosBundleId: 'com.example.certin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmDiQdPOumm9NaoZn-lCA9YOrqCbI16Yw',
    appId: '1:157676629757:web:15fd9b1ffd0dd2b9f81894',
    messagingSenderId: '157676629757',
    projectId: 'certin-70cf9',
    authDomain: 'certin-70cf9.firebaseapp.com',
    storageBucket: 'certin-70cf9.appspot.com',
    measurementId: 'G-6RSKLM5EHE',
  );
}
